### ISSUE TITLE
页面在已经获得token的情况下，重新进入页面请求获取路由集合接口时，如果接口报错，页面会不停的进行请求

### ISSUE THREAD

**Issue by zyhnbyyds** [soybeanjs/soybean-admin-antd#10]
https://github.com/soybeanjs/soybean-admin-antd/assets/83394286/32c4e654-4efd-4145-805d-8bfd03d3fff1

**Comment by zyhnbyyds** [comment]
我用的是soybean-admin-antd的apifox测试接口，可通过
1、修改.env文件为动态路由
2、登录，
3、修改.env.test文件中的api地址来模拟请求失败，刷新页面，就会出现上图的情况

**Comment by honghuangdc** [comment]
这个接口有错误的话，得加个错误后的处理，清空用户登录态回到登录页

**Comment by zyhnbyyds** [comment]
好的
