### ISSUE TITLE
项目dev启动时,下拉交互巨卡

### ISSUE THREAD

**Issue by ques666** [soybeanjs/soybean-admin-antd#2]
项目dev启动时,下拉交互巨卡

升级devtools到最新版本（"vite-plugin-vue-devtools": "7.0.6"）可解决

**Comment by honghuangdc** [comment]
已升级依赖 [854ce36](https://github.com/soybeanjs/soybean-admin-antd/commit/854ce3639e8b9b5c4e039c471df815ec4bc2ebe2)
