### ISSUE TITLE
[Bug]: 左侧菜单栏在缩小之后 部分图标不居中

### ISSUE THREAD

**Issue by hllkk** [soybeanjs/soybean-admin-antd#33]
### 软件版本

Node v20.12.0  

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

运行项目，点击缩小右侧菜单栏图标，即可复现

### 期望的结果是什么？

缩小菜单栏后，图标居中

### 实际的结果是什么？

只有首页和关于的图标居中展示，其他的都偏右一点。

**Comment by honghuangdc** [comment]
fix 4355b6e
