### ISSUE TITLE
[Bug]: useTable 使用有vue系统级别报错

### ISSUE THREAD

**Issue by caohuiboss** [soybeanjs/soybean-admin-antd#39]
### 软件版本

最新版本

### 运行环境

MacOS

### 运行架构

AMD64

### 重现步骤

使用 import { useTable } from '@/hooks/common/table'; 
useTable 使用会经常性报错

1. 使用的方式
<img width="941" alt="image" src="https://github.com/user-attachments/assets/4c190ec4-3625-4d25-a385-9c55f83d8eb0">

2. 出现的报错
<img width="1581" alt="image" src="https://github.com/user-attachments/assets/6ef3a430-bced-4244-8799-7b3acaf2dbae">

这是经常性的 一旦出现报错 必将导致整个项目停摆了 

### 期望的结果是什么？

useTable不会出现系统级的错误

### 实际的结果是什么？

<img width="1581" alt="image" src="https://github.com/user-attachments/assets/789a476d-2458-4c96-8285-180f5c79cd93">
报错了 项目无法切换路由 或者操作其他了 除非刷星

**Comment by caohuiboss** [comment]
> 你的某个页面的template标签里有多个根节点

大佬不对啊 我就只写了一个页面 并且这个页面我注释了 ATable 就不报错了 

![Uploading image.png…]()

**Comment by caohuiboss** [comment]
> 你的某个页面的template标签里有多个根节点

大佬不对啊 我就只写了一个页面 并且这个页面我注释了 ATable 就不报错了

**Comment by honghuangdc** [comment]
这个和useTable没关系，大概率是后端返回的数据问题
