### ISSUE TITLE
Remove router/elegant and typings/elegant-router.d.ts. Then run dev and something strange happens

### ISSUE THREAD

**Issue by baixjian** [soybeanjs/soybean-admin-antd#4]
<img width="1908" alt="image" src="https://github.com/soybeanjs/soybean-admin-antd/assets/109275788/b2830116-541b-44ef-9a90-b66ada9dc3bb">
The suspicion is layout.blank$, not layout.base$

**Comment by honghuangdc** [comment]
参照这个 https://github.com/soybeanjs/soybean-admin/issues/338
