### ISSUE TITLE
[Bug]: useTable 报错 

### ISSUE THREAD

**Issue by caohuiboss** [soybeanjs/soybean-admin-antd#40]
### 软件版本

最新版本

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

参考 https://github.com/soybeanjs/soybean-admin-antd/issues/39
虽然大佬说是多个根节点原因 但是我确实没找到这块代码，但是我发现我这么使用的话就没有这种报错了immediate设置为false，首次执行改到onMounted 且await执行就不会报错

<img width="906" alt="image" src="https://github.com/user-attachments/assets/3c8accc5-eb09-4970-9995-15b04e6b40ed">

### 期望的结果是什么？

正常执行

### 实际的结果是什么？

报错

**Comment by honghuangdc** [comment]
排查下表格数据问题，看示例页面也是没这种问题
