### ISSUE TITLE
[功能]:请问下用户详情的tab是否应该替换用户管理，而不是新开一个

### ISSUE THREAD

**Issue by wangqiqi95** [soybeanjs/soybean-admin-antd#41]
### 描述

目前从用户管理的列表页跳转至用户详情时，会新打开一个tab。如图
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/5073d1f6-0e4d-4bf0-94c7-102dab041db4">

是否有vben类似的平级模式：https://v2.vben.pro/#/feat/breadcrumb/flat

### 建议的解决方案

希望能有个类似的模式供选择，谢谢

**Comment by honghuangdc** [comment]
暂时不考虑
可以自行通过以下方法实现：
打开详情页时，关闭列表页的tab
