### ISSUE TITLE
[Bug]: 电脑端响应式css显示异常

### ISSUE THREAD

**Issue by dongCode** [soybeanjs/soybean-admin-antd#48]
### 软件版本

1.3.7

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

![image](https://github.com/user-attachments/assets/47d0dbbc-db13-43f1-bb98-8bef276646b0)

### 期望的结果是什么？

显示正常

### 实际的结果是什么？

显示尺寸不正常

**Comment by honghuangdc** [comment]
描述的详细点

**Comment by Azir-11** [comment]
看着挺正常的啊，你觉得这个《显示正常》是个什么样的尺寸呢？

**Comment by honghuangdc** [comment]
问题没描述清楚，关掉了
