### ISSUE TITLE
有计划同步soyben-admin的代码嘛

### ISSUE THREAD

**Issue by baixjian** [soybeanjs/soybean-admin-antd#8]

**Comment by Azir-11** [comment]
有，但是现在人手不是很够，需要一些时间

**Comment by baixjian** [comment]
> 有，但是现在人手不是很够，需要一些时间

是不是已经开始同步啦，🎉

**Comment by huangxh1** [comment]
> 表格部份还有这些样式需要完善，目前管理页面只同步了角色页面

大佬，抽个空吧表格整整嘛，那个表格样式问题还挺多的。我是一个java后端，css样式实在弄着头痛

**Comment by Azir-11** [comment]
> > 表格部份还有这些样式需要完善，目前管理页面只同步了角色页面
> 
> 大佬，抽个空吧表格整整嘛，那个表格样式问题还挺多的。我是一个java后端，css样式实在弄着头痛

感谢您的反馈，有时间会处理的，不过我们平常也是要上班什么的，纯为爱发电，目前antdv版本的用户量不多，社区力量可能还不够强大，希望能理解

**Comment by honghuangdc** [comment]
已同步 cedf671
